import '@/app/ui/global.css';
import { sora } from '@/app/ui/fonts';
import { space } from '@/app/ui/fonts';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${sora.className} antialiased`}>{children}</body>
    </html>
  )
}
